### ISSUE TITLE
how to access sharedpreference(referrer string) inside hybrid application

### ISSUE THREAD

**Issue by anshulklr** [mooreds/android-referrer-plugin#1]
@mooreds 
from the code i can see that the referrer is getting saved in the sharedpreferences but can you tell me the way to access it for using it inside the app.

**Comment by mooreds** [comment]
Not sure what version of cordova you are using, but you might have to write a plugin to access the shared preferences:

https://stackoverflow.com/questions/17000135/which-way-is-preferred-to-store-my-android-application-settings-to-access-them-v

https://stackoverflow.com/questions/10786172/android-getdefaultsharedpreferences/10786739#10786739

I don't know if there is an out of the box solution.  Sorry.
